### ISSUE TITLE
All tests failed use yarn install dependencies

### ISSUE THREAD

**Issue by script-money** [onflow/flow-js-testing#37]
### Instructions

`yarn test` cause error `Failure: Cannot coerce to Uint8Array: object`

### Problem

I use `yarn` to install testing dependencies, run `yarn test`, all of cases will fail. And show below
```
 assert.fail(received, expected)

    Message:
      Failure: Cannot coerce to Uint8Array: object

      at new arguments (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:81:961)
      at Object.goog.asserts.fail (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:84:172)
      at Function.setAddress [as bytesAsU8] (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:424:29)
      at proto.flow.access.GetAccountAtLatestBlockRequest.GetAccountAtLatestBlockRequest [as getAddress_asU8] (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3684:60)
      at Function.GetAccountAtLatestBlockRequest [as serializeBinaryToWriter] (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3651:19)
      at proto.flow.access.GetAccountAtLatestBlockRequest.serializeBinary (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3635:19)
      at Object.t.frameRequest (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24529)
      at e.send (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:12769)
      at Object.OK [as unary] (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24335)
      at node_modules/flow-cadut/node_modules/@onflow/sdk/src/send/unary.js:12:34
```

But use `npm install` then `yarn test` works fine.

### Steps to Reproduce

1. `git clone https://github.com/onflow/kitty-items.git`
2. `cd cadence/lib/js/`
3. `yarn`
4. `yarn test`

### Context

macOS Big Sur 11.4
node v14.15.1
yarn 1.22.10
flow-cli 0.23.0

**Comment by MaxStalker** [comment]
@script-money this shall be fixed now. Try to pull `main` branch and try again.
