### ISSUE TITLE
All tests failing after installing npm install updates dependencies

### ISSUE THREAD

**Issue by flockonus** [onflow/flow-js-testing#38]
### Instructions

1. git clone https://github.com/KLKTN/nfts

2. `npm test` -- this should work because `node_modules/` are committed

3. Now run `npm i` to update dependencies and run `npm test` -- this fails as some internal dependency seems incompatible. So it seems updating packages have some deep dependency out of sync

### Problem

Example of a test failing after `npm i`, all messages are like this:

```
  ● Test Account Creation › Create Minter Account

    assert.fail(received, expected)

    Message:
      Failure: Cannot coerce to Uint8Array: object

      at new arguments (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:81:961)
      at Object.goog.asserts.fail (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:84:172)
      at Function.setAddress [as bytesAsU8] (node_modules/@onflow/protobuf/dist/webpack:/node_modules/google-protobuf/google-protobuf.js:424:29)
      at proto.flow.access.GetAccountAtLatestBlockRequest.GetAccountAtLatestBlockRequest [as getAddress_asU8] (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3684:60)
      at Function.GetAccountAtLatestBlockRequest [as serializeBinaryToWriter] (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3651:19)
      at proto.flow.access.GetAccountAtLatestBlockRequest.serializeBinary (node_modules/@onflow/protobuf/dist/webpack:/src/generated/flow/access/access_pb.js:3635:19)
      at Object.t.frameRequest (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24529)
      at e.send (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:12769)
      at Object.OK [as unary] (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24335)
      at node_modules/flow-cadut/node_modules/@onflow/sdk/src/send/unary.js:12:34
```

### Context

Originally installed packages maybe 2~3 weeks ago, which has been working. But trying to initialize this new repo today gave this error.

Using node 14
"flow-js-testing": "^0.1.10"

**Comment by flockonus** [comment]
@MaxStalker the error message seems quite similar to #37, could be a similar cause?

**Comment by MaxStalker** [comment]
Hey, @flockonus!
Can you try to pull latest version from npm and try again?

**Comment by mwufi** [comment]
Same here...

**Comment by flockonus** [comment]
Hey @MaxStalker sorry the delay, I missed this message. It now works for me!

@mwufi  what's the output if you download https://github.com/KLKTN/nfts, does `npm i` and `npm test` ?

**Comment by mwufi** [comment]
Hey @flockonus ! I'm getting a bunch of these errors 😔
```
    Response closed without headers
```

Is there something I have to do beforehand???

**Comment by flockonus** [comment]
@mwufi did you [install flow-cli](https://docs.onflow.org/flow-cli/install/)?
Might be the step missing

**Comment by mwufi** [comment]
Yeah, I did.... 

Side note... how do we use the `flow.json` in that repo?

When I run `flow emulator` I get
```
deployment contains nonexisting account testnet-minter
```

**Comment by flockonus** [comment]
@mwufi flow.json is loaded from the js test suite.
make sure your flow emulator **is not** running when you run the test suite, they may conflict.
In fact i'd advise to reboot your computer once to make sure the is no active process

**Comment by mwufi** [comment]
Hi again! Yeah, I'm still having trouble with this.... the steps that you mentioned worked for you, though?

(clone repo, npm i, npm test)?

I'm trying to browse some other repos but I run into problems. for example, https://github.com/wutayng/moments-cadence

Sorry for all the trouble!! I feel like I have a lot of debugging issues with this library lol

**Comment by mwufi** [comment]
OMFG I have to run `./setup-accounts.sh` first for that one... 

1. Set up the emulator: `flow emulator`
2. Set up the accounts: `./setup-accounts.sh`
3. Run the tests: `npm test`

Then it works fine. Thanks Fabiano!

![image](https://user-images.githubusercontent.com/30219253/125987114-640581c6-4c22-4da8-bd90-2fe5bb254938.png)

**Comment by figs999** [comment]
If anyone else was still having this issue, I solved it by installing jest-environment-uint8array with node and changing my jest.config,js to include:

**_"testEnvironment": "jest-environment-uint8array"_**
