### ISSUE TITLE
Transaction signing error

### ISSUE THREAD

**Issue by beshup** [onflow/flow-js-testing#41]
### Problem

flow-js-testing isn't signing transactions properly with emulator-account. 

### Steps to Reproduce

Run in first terminal:

```
mkdir /tmp/test1
cd /tmp/test1
flow init
flow emulator -v
```

In second terminal:

```
cd /tmp/test1
npm install flow-js-testing jest @babel/core @babel/preset-env babel-jest @onflow/types
Install and setup (https://github.com/onflow/flow-js-testing/blob/master/docs/installation.md)
Create deploy.test.js (https://github.com/onflow/flow-js-testing/blob/master/docs/examples/basic.md)
npx jest
```

Error:
```
FAIL  ./deploy.test.js
  Accounts
    ✕ Create Accounts (241 ms)

  ● Accounts › Create Accounts

    thrown: "execution error code 1006: [Error Code: 1006] invalid proposal key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account f8d6e0586b0a20c7 does not have a valid signature: signature is not valid"

       9 |
      10 | describe("Accounts", () => {
    > 11 |   test("Create Accounts", async () => {
         |   ^
      12 |     const Alice = await getAccountAddress("Alice");
      13 |     const Bob = await getAccountAddress("Bob");
      14 |     const Charlie = await getAccountAddress("Charlie");

      at deploy.test.js:11:3
      at Object.<anonymous> (deploy.test.js:10:1)
```

**Comment by beshup** [comment]
Yes, we can close it. Sorry for the late response!

**Comment by janhesters** [comment]
@beshup How did you fix this? I'm getting the same error.
