### ISSUE TITLE
beforeEach is undefined

### ISSUE THREAD

**Issue by Screendead** [onflow/flow-js-testing#82]
### Problem

(This might be a problem with `flow-cli` rather than `flow-js-testing`)
After running `brew update && brew upgrade flow-cli` the following error appears:

```
thrown: undefined

      52 |
      53 | describe("Project", () => {
    > 54 |   beforeEach(async () => {
         |   ^
      55 |     const basePath = path.resolve(__dirname, "./cadence");
      56 |     const port = 8080;
      57 |     init(basePath, port);

      at Project.test.js:54:3
      at Object.<anonymous> (Project.test.js:53:1)
```

### Steps to Reproduce

Use the latest version of `flow-cli`, and the problem occurs from `flow-js-testing` 0.1.15 to 0.2.2

### Context

Currently working on testing a contract in preparation for deployment to mainnet. The project is ready for release, so this is preventing the last step we need to deploy and holding up the project.

**Comment by mrpowergage** [comment]
same issue for me (working on the project with @Screendead )

**Comment by KSlashh** [comment]
seems flow-js-testing/emulator try to start emulator with --http-port flag , which is removed by latest flow cli

**Comment by MaxStalker** [comment]
@Screendead @mrpowergage @KSlashh I'm on this problem right now, there should be a fix soon :)

**Comment by MaxStalker** [comment]
I've released `0.2.3-alpha.1`.
@KSlashh @mrpowergage @Screendead can you try to update the package and check if it works for you?

**Comment by Screendead** [comment]
Thanks for your quick fix @MaxStalker - might be a silly question but my `flow-cli` is currently installed via Homebrew; I tried `brew install flow-cli@0.2.3-alpha.1` but it didn't find anything. How should I be upgrading?

**Comment by KSlashh** [comment]
> Thanks for your quick fix @MaxStalker - might be a silly question but my `flow-cli` is currently installed via Homebrew; I tried `brew install flow-cli@0.2.3-alpha.1` but it didn't find anything. How should I be upgrading?

Try to update flow-js-testing .

**Comment by Screendead** [comment]
> > Thanks for your quick fix @MaxStalker - might be a silly question but my `flow-cli` is currently installed via Homebrew; I tried `brew install flow-cli@0.2.3-alpha.1` but it didn't find anything. How should I be upgrading?
> 
> Try to update flow-js-testing .

Ah, so it was indeed a silly question! Thanks :)
